"""initial schema

Revision ID: 6ceb0f7f3598
Revises: 
Create Date: 2026-08-24 10:16:26.060166+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6ceb0f7f3598'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='reservation_status', native_enum=False, length=20), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED')", name=op.f('ck_reservations_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('idempotency_key', name='uq_reservations_idempotency_key')
    )
    op.create_index('ix_reservations_status_expires_at', 'reservations', ['status', 'expires_at'], unique=False)
    op.create_table('reservation_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_events_reservation_id_reservations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_events'))
    )
    op.create_index(op.f('ix_reservation_events_reservation_id'), 'reservation_events', ['reservation_id'], unique=False)
    op.create_table('reservation_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_reservation_items_qty_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reservation_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_items_reservation_id_reservations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_items')),
    sa.UniqueConstraint('reservation_id', 'product_id', name='uq_reservation_items_reservation_id')
    )
    op.create_index(op.f('ix_reservation_items_product_id'), 'reservation_items', ['product_id'], unique=False)
    op.create_table('stock',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_stock_quantity_non_negative')),
    sa.CheckConstraint('reserved <= quantity', name=op.f('ck_stock_reserved_le_quantity')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_stock_reserved_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_stock'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_index(op.f('ix_reservation_items_product_id'), table_name='reservation_items')
    op.drop_table('reservation_items')
    op.drop_index(op.f('ix_reservation_events_reservation_id'), table_name='reservation_events')
    op.drop_table('reservation_events')
    op.drop_index('ix_reservations_status_expires_at', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('products')
    # ### end Alembic commands ###
